app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
    
aluno_list:
    path: /aluno
    controller: App\Controller\AlunoController::list
#    'title' => 'Página de usuários'
index:
    path: /
    controller: App\Controller\DefaultController::index
